version: 0.0
os: linux
files:
  - source: my-app-1.0-SNAPSHOT.jar
    destination: /opt/my-app
hooks:
  ApplicationStop:
    - location: jenkins/scripts/stop_server.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: jenkins/scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: jenkins/scripts/start_server.sh
      timeout: 300
      runas: root